# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7d89083e1b5416bec915651d43e0ca2b2e8847b0916be093d3d51b34012d9c2781a02d5c6586c7b607e187eee171443754b31c43360a3d1ac6c5aad40477c4c

test:
  secret_key_base: 08c81a875f0f73cb98f155be8c0453139b30b28060c81b1e313ebafc554560c7d4433d687ae2e62d60c908daf7bedd4baba07eb81d69c637d783e1ba3e552211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
